[package]
name = "wible"
version = "0.1.0"
authors = ["Syfaro <syfaro@huefox.com>"]
edition = "2018"

[dependencies]
bitflags = "1.2"
log = "0.4"
winrt = "0.7"

[dev-dependencies]
pretty_env_logger = "0.4"
